# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/v1/todolists.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/v1/todolists.proto',
  package='todolists',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x18proto/v1/todolists.proto\x12\ttodolists\"!\n\x11\x43reateListRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"+\n\x0f\x43reateListReply\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t2O\n\tTodoLists\x12\x42\n\x06\x43reate\x12\x1c.todolists.CreateListRequest\x1a\x1a.todolists.CreateListReplyb\x06proto3'
)




_CREATELISTREQUEST = _descriptor.Descriptor(
  name='CreateListRequest',
  full_name='todolists.CreateListRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='todolists.CreateListRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=72,
)


_CREATELISTREPLY = _descriptor.Descriptor(
  name='CreateListReply',
  full_name='todolists.CreateListReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='todolists.CreateListReply.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='todolists.CreateListReply.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['CreateListRequest'] = _CREATELISTREQUEST
DESCRIPTOR.message_types_by_name['CreateListReply'] = _CREATELISTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateListRequest = _reflection.GeneratedProtocolMessageType('CreateListRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATELISTREQUEST,
  '__module__' : 'proto.v1.todolists_pb2'
  # @@protoc_insertion_point(class_scope:todolists.CreateListRequest)
  })
_sym_db.RegisterMessage(CreateListRequest)

CreateListReply = _reflection.GeneratedProtocolMessageType('CreateListReply', (_message.Message,), {
  'DESCRIPTOR' : _CREATELISTREPLY,
  '__module__' : 'proto.v1.todolists_pb2'
  # @@protoc_insertion_point(class_scope:todolists.CreateListReply)
  })
_sym_db.RegisterMessage(CreateListReply)



_TODOLISTS = _descriptor.ServiceDescriptor(
  name='TodoLists',
  full_name='todolists.TodoLists',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=198,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='todolists.TodoLists.Create',
    index=0,
    containing_service=None,
    input_type=_CREATELISTREQUEST,
    output_type=_CREATELISTREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOLISTS)

DESCRIPTOR.services_by_name['TodoLists'] = _TODOLISTS

# @@protoc_insertion_point(module_scope)
